// Constantes para tipos de mensajes de WhatsApp
const _PROTOCOL_MESSAGE_ALBUM = 14;
const _PROTOCOL_MESSAGE_REVOKE = 7;
const _PROTOCOL_MESSAGE_EPHEMERAL_SETTING = 18;

// Constantes para tipos de mensajes
const _MESSAGE_TYPE_CHAT = 'chat';
const _MESSAGE_TYPE_IMAGE = 'image';
const _MESSAGE_TYPE_VIDEO = 'video';
const _MESSAGE_TYPE_AUDIO = 'audio';
const _MESSAGE_TYPE_DOCUMENT = 'document';
// const _MESSAGE_TYPE_STICKER = 'sticker'; // Soporte deshabilitado
const _MESSAGE_TYPE_LOCATION = 'location';
const _MESSAGE_TYPE_CONTACT = 'contact';
const _MESSAGE_TYPE_ALBUM = 'album';
const _MESSAGE_TYPE_CALL = 'call';

// Constantes para timeouts y límites
const _ALBUM_WAIT_TIMEOUT = 10000; // 10 segundos para esperar mensajes de álbum
const _ALBUM_MAX_IMAGES = 30; // Máximo número de imágenes en un álbum
const _PROCESSED_MESSAGES_MAX_SIZE = 1000;
const _PROCESSED_MESSAGES_KEEP_SIZE = 500;

module.exports = {
  PROTOCOL_MESSAGE_ALBUM: _PROTOCOL_MESSAGE_ALBUM,
  PROTOCOL_MESSAGE_REVOKE: _PROTOCOL_MESSAGE_REVOKE,
  PROTOCOL_MESSAGE_EPHEMERAL_SETTING: _PROTOCOL_MESSAGE_EPHEMERAL_SETTING,
  MESSAGE_TYPE_CHAT: _MESSAGE_TYPE_CHAT,
  MESSAGE_TYPE_IMAGE: _MESSAGE_TYPE_IMAGE,
  MESSAGE_TYPE_VIDEO: _MESSAGE_TYPE_VIDEO,
  MESSAGE_TYPE_AUDIO: _MESSAGE_TYPE_AUDIO,
  MESSAGE_TYPE_DOCUMENT: _MESSAGE_TYPE_DOCUMENT,
  MESSAGE_TYPE_LOCATION: _MESSAGE_TYPE_LOCATION,
  MESSAGE_TYPE_CONTACT: _MESSAGE_TYPE_CONTACT,
  MESSAGE_TYPE_ALBUM: _MESSAGE_TYPE_ALBUM,
  MESSAGE_TYPE_CALL: _MESSAGE_TYPE_CALL,
  ALBUM_WAIT_TIMEOUT: _ALBUM_WAIT_TIMEOUT,
  ALBUM_MAX_IMAGES: _ALBUM_MAX_IMAGES,
  PROCESSED_MESSAGES_MAX_SIZE: _PROCESSED_MESSAGES_MAX_SIZE,
  PROCESSED_MESSAGES_KEEP_SIZE: _PROCESSED_MESSAGES_KEEP_SIZE
};
